### ISSUE TITLE
Not generating [Links]("/properly")

### ISSUE THREAD

**Issue by soverysour** [bakpakin/luamd#7]
Say I got `[Links]("/properly")`and want to parse this from md to html. The result is going to be:

```html
<a href="" properly""="">Links</a>
```

For `[Links]("http://www.example.com/reallycoolthing")` : 

```html
<a href="" http:="" www.example.com="" reallycoolthing""="">Links</a>
```

`[Links]("#something")` : 
```html
<a href="" #something""="">Links</a>
```

It never parses it into something that's redirectionish. 

Is this a known lack of feature or bug, or on a TODO list?

*Got the `md.lua` through LuaRocks.

**Comment by Frenzie** [comment]
Is that syntax part of CommonMark or some other MarkDown flavor? I've never used (nor seen afaik) anything other than `[linktext](linktarget)`.

Edit: no, per CommonMark it looks like md.lua behaves incorrectly (as `title` attributes aren't implemented yet) but your sample still shouldn't result in what you want http://spec.commonmark.org/0.28/#links

Regular use like this works just fine.
```
[Links](/properly)
[Links](http://www.example.com/reallycoolthing)
[Links](#something)
```

The expected result for
```
[link]("title")
 ```
is
```
<p><a href="%22title%22">link</a></p>
```

Or in your case the outcome should be like this for all of them per-spec:
```
<p><a href="%22properly%22">Links</a></p>
```

**Comment by soverysour** [comment]
Oh my god did I seriously quote this thing...

Sorry for this, my brain really hasn't been clicking lately, and this is one of its nonclicks.

Thanks for making me realise :D

**Comment by Frenzie** [comment]
I recommend a quick sanity check with the amazing Pandoc (or even GitHub's preview). ;-)
